#!/usr/bin/env python3
"""Regenerates the committed test media that need ffmpeg.

    .venv/bin/python scripts/generar-fixtures.py            # media that need ffmpeg
    .venv/bin/python scripts/generar-fixtures.py --out DIR  # also write the full tree to DIR

Everything else — the throwaway test CA and every C2PA-signed fixture — is generated by
pytest at session time in a temporary directory (`tests/fabrica.py`), so no private key
is ever committed. `--out` writes that full tree for inspection; the test key lands in
DIR too, so keep DIR outside the repository.

The AIGC MP3/MP4 use exactly the `ffmpeg -metadata AIGC=… -movflags use_metadata_tags`
command shown in the TC260 practice guides.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
FIX = RAIZ / "tests" / "fixtures"
sys.path.insert(0, str(RAIZ))

from tests import fabrica  # noqa: E402


def ffmpeg(*a: str) -> None:
    subprocess.run(["ffmpeg", "-v", "error", "-y", *a], check=True)


def medios_ffmpeg() -> None:
    aigc = json.dumps(fabrica.AIGC, ensure_ascii=False)
    for d in ("base", "mp3", "mp4"):
        (FIX / d).mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as t:
        d = Path(t)
        ffmpeg(
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=0.3",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "32k",
            str(FIX / "base/sin-marcas.mp3"),
        )
        ffmpeg(
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=32x32:rate=5",
            "-t",
            "0.6",
            "-pix_fmt",
            "yuv420p",
            "-c:v",
            "libx264",
            str(FIX / "base/sin-marcas.mp4"),
        )
        ffmpeg(
            "-i",
            str(FIX / "base/sin-marcas.mp3"),
            "-metadata",
            f"AIGC={aigc}",
            "-c",
            "copy",
            str(d / "a.mp3"),
        )
        ffmpeg(
            "-i",
            str(FIX / "base/sin-marcas.mp4"),
            "-metadata",
            f"AIGC={aigc}",
            "-movflags",
            "use_metadata_tags",
            "-c",
            "copy",
            str(d / "a.mp4"),
        )
        shutil.copy(d / "a.mp3", FIX / "mp3/aigc.mp3")
        shutil.copy(d / "a.mp4", FIX / "mp4/aigc.mp4")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, help="write the full generated tree here")
    args = ap.parse_args()
    if shutil.which("ffmpeg"):
        medios_ffmpeg()
    else:
        print("warning: ffmpeg not found; committed MP3/MP4 media left as they are")
    if args.out:
        shutil.copytree(FIX, args.out, dirs_exist_ok=True)
        fabrica.genera(args.out)
        print(f"full fixture tree in {args.out} (contains the throwaway TEST key)")
